seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: tb_logs
      name: vit_base_patch16_finetune_celeba_pretrain
      version: find_lr
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      agg_key_funcs: null
      agg_default_func: null
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: null
  devices: 1
  gpus: 4
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: true
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: true
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  data_path: /home/xing/datasets/CelebA/
  arch: vit_base_patch16
  pretrained: false
  global_pool: true
  drop_path: 0.1
  smoothing: 0.1
  lr: 0.001
  min_lr: 1.0e-06
  momentum: 0.9
  weight_decay: 0.05
  batch_size: 128
  workers: 4
  warmup_epochs: 5
ckpt_path: null
